name: Deploy to FTP Server

on:
  push:
    branches: [ main ]  # Trigger on pushes to main branch
  workflow_dispatch:    # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js (if you need to build the project)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    # Uncomment and modify if you need to build your project
    # - name: Install dependencies
    #   run: npm install
    #   
    # - name: Build project
    #   run: npm run build
        
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps  # Use 'ftp' for regular FTP, 'ftps' for FTP over TLS
        port: 21        # Default FTP port, change if needed
        local-dir: ./   # Local directory to upload (current directory)
        server-dir: /home/digitald/fugitivetexts.net/no-time   # Remote directory on your web host
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.github/**
          **/README.md
          **/.gitignore
        
    - name: Notify deployment success
      run: echo "Deployment completed successfully!"
